import type { Game, Devlog, News, Movie, PortfolioItem, SiteSettings } from './types';

// ─────────────────────────────────────────────────────────────
// MODO DEMO — Estos datos se muestran cuando Supabase aún no
// está configurado. Al conectar tu proyecto Supabase y ejecutar
// supabase/schema.sql, el sitio usará tu base de datos real.
// ─────────────────────────────────────────────────────────────

export const demoGames: Game[] = [
  {
    id: 'demo-velador',
    slug: 'el-velador',
    title: 'El Velador',
    tagline: 'Nadie debería quedarse en la escuela después del anochecer.',
    description:
      'Horror atmosférico en primera persona. Eres el velador nocturno de una escuela antigua y algo más recorre los pasillos contigo. Explora, escucha y sobrevive hasta el amanecer.',
    status: 'en_desarrollo',
    progress: 18,
    progress_categories: { Gameplay: 22, Arte: 10, 'Programación': 30, Audio: 8, Historia: 45, UI: 12, 'Optimización': 5 },
    engine: 'Unity',
    technologies: ['Unity', 'C#', 'Blender', 'FMOD'],
    release_estimate: 'Demo — 2027',
    cover_url: '/covers/velador.svg',
    trailer_url: null,
    demo_url: null,
    story:
      'La escuela primaria *Benito Juárez* cerró hace años, pero el municipio sigue pagando a un velador. Nadie dura más de un mes en el puesto.\n\nEsta noche es tu primer turno. Tienes una lámpara, un manojo de llaves y una libreta con las notas del velador anterior. Las últimas páginas están escritas con otra letra.',
    features: [
      { title: 'Exploración con lámpara', description: 'La luz es tu única herramienta: revela, pero también delata tu posición.' },
      { title: 'Audio 3D posicional', description: 'El sonido cuenta la historia. Escuchar bien es sobrevivir.' },
      { title: 'Noches procedurales', description: 'Cada turno cambia rutas, eventos y apariciones.' },
      { title: 'Sin combate', description: 'No puedes pelear. Solo esconderte, correr y pensar.' },
    ],
    characters: [
      { name: 'El Velador', description: 'Tú. Un tipo normal que necesitaba el trabajo.' },
      { name: 'Don Ramiro', description: 'El velador anterior. Su libreta es tu única guía… y tu primera advertencia.' },
    ],
    gallery: ['/covers/velador.svg', '/covers/velador-alt.svg'],
    roadmap: [
      { date: '2026 · Q2', title: 'Inicio del proyecto', description: 'Concepto, documento de diseño y primeras pruebas en Unity.', done: true },
      { date: '2026 · Q3', title: 'Primer prototipo', description: 'Movimiento en primera persona, lámpara e interacciones básicas.', done: false },
      { date: '2026 · Q4', title: 'Sistema de sonido y tensión', description: 'Audio posicional, eventos de susto y ciclo de la noche.', done: false },
      { date: '2027 · Q1', title: 'IA de la entidad', description: 'Comportamiento que reacciona a luz y ruido.', done: false },
      { date: '2027 · Q2', title: 'Demo privada', description: 'Pruebas con jugadores cercanos.', done: false },
      { date: '2027 · Q3', title: 'Demo pública', description: 'Publicación de la demo en itch.io.', done: false },
    ],
    goals: ['Terminar el prototipo jugable de la primera noche', 'Definir el diseño sonoro base', 'Publicar el primer devlog en video'],
    faq: [
      { q: '¿En qué plataformas saldrá?', a: 'Primero PC (itch.io / Steam). Consolas se evaluarán después del lanzamiento.' },
      { q: '¿Tendrá demo gratuita?', a: 'Sí. La demo pública está planeada dentro del roadmap.' },
      { q: '¿Es un juego de combate?', a: 'No. Es horror de evasión: esconderse, observar y sobrevivir.' },
    ],
    featured: true,
    sort: 1,
    created_at: '2026-05-01',
  },
  {
    id: 'demo-archivo',
    slug: 'archivo-clave',
    title: 'Archivo Clave',
    tagline: 'Operativo Encubierto — un juego de espías por equipos, en el navegador.',
    description:
      'Juego multijugador de palabras clave estilo espionaje. Dos equipos, un tablero de nombres en clave y jefes de inteligencia dando pistas. Corre directo en el navegador con WebRTC, sin servidor.',
    status: 'demo',
    progress: 80,
    progress_categories: { Gameplay: 90, Arte: 70, 'Programación': 85, Audio: 40, Historia: 60, UI: 85, 'Optimización': 75 },
    engine: 'Web (HTML5)',
    technologies: ['JavaScript', 'PeerJS', 'WebRTC', 'HTML/CSS'],
    release_estimate: 'Jugable ahora',
    cover_url: '/covers/archivo.svg',
    trailer_url: null,
    demo_url: '#',
    story: null,
    features: [
      { title: 'Multijugador P2P', description: 'Conexión directa entre jugadores con WebRTC. Sin backend.' },
      { title: 'Un solo archivo', description: 'Todo el juego vive en un HTML: fácil de hospedar en cualquier hosting estático.' },
      { title: 'Partidas rápidas', description: 'Salas por código, roles de agente y jefe de inteligencia.' },
    ],
    characters: [],
    gallery: ['/covers/archivo.svg'],
    roadmap: [
      { date: '2026 · Q2', title: 'Versión 3 estable', description: 'Auditoría de red y corrección para hosting estático.', done: true },
      { date: '2026 · Q3', title: 'Modo espectador', description: 'Permitir observar partidas en curso.', done: false },
    ],
    goals: ['Pulir reconexión de jugadores', 'Agregar sonidos de interfaz'],
    faq: [{ q: '¿Necesito instalar algo?', a: 'No. Se juega directo en el navegador, en escritorio o móvil.' }],
    featured: false,
    sort: 2,
    created_at: '2026-06-01',
  },
];

export const demoDevlogs: Devlog[] = [
  {
    id: 'demo-devlog-2',
    game_id: 'demo-velador',
    slug: 'velador-devlog-002-lampara',
    version: 'v0.0.2',
    title: 'La lámpara ya funciona (y ya da miedo)',
    date: '2026-06-28',
    time_invested: '14 h',
    summary: 'Sistema de lámpara con batería, parpadeo y sombras dinámicas. Primeras pruebas de iluminación en el pasillo principal.',
    content:
      'Esta semana el objetivo era uno solo: que la **lámpara** se sintiera viva.\n\n### Qué se hizo\n\nLa lámpara ahora consume batería, parpadea cuando está por agotarse y proyecta sombras dinámicas sobre el pasillo. Probé tres perfiles de luz distintos hasta encontrar uno que ilumina lo justo: suficiente para avanzar, no suficiente para sentirte seguro.\n\n### Lo que aprendí\n\nEl miedo no está en la oscuridad total, está en la **frontera** entre lo que ves y lo que no.',
    cover_url: '/covers/velador-alt.svg',
    gallery: [],
    goals: ['Perfil de luz definitivo', 'Sonido de interruptor y parpadeo'],
    changes: [
      { type: 'nuevo', text: 'Sistema de batería para la lámpara' },
      { type: 'nuevo', text: 'Parpadeo procedural al quedar poca carga' },
      { type: 'mejora', text: 'Sombras dinámicas en el pasillo principal' },
      { type: 'arreglo', text: 'La luz ya no atraviesa las puertas cerradas' },
    ],
    status: 'published',
    created_at: '2026-06-28',
  },
  {
    id: 'demo-devlog-1',
    game_id: 'demo-velador',
    slug: 'velador-devlog-001-inicio',
    version: 'v0.0.1',
    title: 'Comienza el turno: nace El Velador',
    date: '2026-06-10',
    time_invested: '9 h',
    summary: 'Documento de diseño, primer proyecto en Unity y controlador en primera persona caminando por un pasillo gris.',
    content:
      'Todo proyecto empieza con un pasillo gris y un capsule collider.\n\nEsta semana escribí el documento de diseño inicial de **El Velador**, armé el proyecto en Unity y dejé funcionando el controlador en primera persona: caminar, correr, agacharse. Nada de esto es impresionante todavía — pero ya se puede *caminar dentro de la idea*, y eso lo cambia todo.',
    cover_url: '/covers/velador.svg',
    gallery: [],
    goals: ['Prototipo de lámpara', 'Blockout del primer pasillo'],
    changes: [
      { type: 'nuevo', text: 'Proyecto base en Unity (URP)' },
      { type: 'nuevo', text: 'Controlador en primera persona' },
      { type: 'nuevo', text: 'Documento de diseño v1' },
    ],
    status: 'published',
    created_at: '2026-06-10',
  },
];

export const demoNews: News[] = [
  {
    id: 'demo-news-1',
    slug: 'nace-odiseo-studio',
    title: 'Bienvenidos a la base de operaciones',
    excerpt: 'Este sitio será el hogar de mis videojuegos, devlogs, reseñas de cine y proyectos. Así se ve el plan.',
    content:
      'Hoy abre oficialmente este sitio: la base de operaciones de todo lo que hago.\n\nAquí vas a poder seguir el desarrollo de **El Velador**, leer devlogs técnicos, encontrar mis reseñas de cine de terror y ciencia ficción, y ver los proyectos en los que trabajo.\n\nEl objetivo es simple: documentar el camino de cero a desarrollador de videojuegos, en público.',
    cover_url: '/covers/velador.svg',
    category: 'Actualización',
    tags: ['sitio', 'estudio'],
    featured: true,
    status: 'published',
    published_at: '2026-07-01T12:00:00Z',
    created_at: '2026-07-01',
  },
  {
    id: 'demo-news-2',
    slug: 'primer-devlog-el-velador',
    title: 'Primer devlog de El Velador ya disponible',
    excerpt: 'Documento de diseño, Unity y un pasillo gris: así empieza todo proyecto de horror.',
    content: 'Ya está publicado el primer devlog de **El Velador**. Puedes leerlo completo en la sección de Devlogs.\n\nSpoiler: todavía no da miedo. Pero ya camina.',
    cover_url: '/covers/velador-alt.svg',
    category: 'Videojuegos',
    tags: ['el-velador', 'devlog'],
    featured: false,
    status: 'published',
    published_at: '2026-06-11T12:00:00Z',
    created_at: '2026-06-11',
  },
  {
    id: 'demo-news-3',
    slug: 'nueva-resena-hereditary',
    title: 'Nueva reseña en Instagram: Hereditary',
    excerpt: 'El terror familiar de Ari Aster, analizado en @fotogramas.malditos.',
    content: 'Ya puedes leer mi opinión completa sobre **Hereditary** en Instagram. La ficha con calificación también está en la sección de Opiniones de este sitio.',
    cover_url: '/covers/cine.svg',
    category: 'Cine',
    tags: ['resena', 'terror'],
    featured: false,
    status: 'published',
    published_at: '2026-06-20T12:00:00Z',
    created_at: '2026-06-20',
  },
];

export const demoMovies: Movie[] = [
  { id: 'm7', title: 'Midsommar', year: 2019, genre: 'Terror', director: 'Ari Aster', duration: 147, rating: 5, review: 'El terror a plena luz del día. Aster cambia la oscuridad por flores y convierte un duelo en pesadilla ritual. Incómoda, hipnótica y hermosa a partes iguales.', poster_url: '/covers/midsommar.jpg', trailer_url: 'https://www.youtube.com/watch?v=1Vnghdsjmd0', platform: 'HBO Max', instagram_url: 'https://www.instagram.com/fotogramas.malditos', featured: false, created_at: '2026-07-03' },
  { id: 'm6', title: 'The Witch', year: 2015, genre: 'Terror', director: 'Robert Eggers', duration: 92, rating: 4.5, review: 'Terror puritano a fuego lento: Eggers construye el mal con silencio, fe y paranoia hasta que la familia se devora sola. Black Phillip ya es leyenda.', poster_url: '/covers/the-witch.jpg', trailer_url: 'https://www.youtube.com/watch?v=iQXmlf3Sefg', platform: 'Prime Video', instagram_url: 'https://www.instagram.com/fotogramas.malditos', featured: false, created_at: '2026-06-29' },
  { id: 'm5', title: 'Obsesión', year: 2026, genre: 'Terror', director: 'Curry Barker', duration: 110, rating: 4, review: 'Entiende algo que pocas películas de terror se animan a tocar: el deseo de que alguien nos quiera, y lo poco que sabemos lo que queremos hasta que lo tenemos. Te da una falsa tranquilidad y, justo cuando bajas la guardia, te regresa de lleno al terror. Deja con ganas de más, pero la recomiendo.', poster_url: '/covers/obsesion.jpg', trailer_url: 'https://www.youtube.com/watch?v=gMC8kkwbIQQ', platform: 'Prime Video', instagram_url: 'https://www.instagram.com/fotogramas.malditos', featured: true, created_at: '2026-06-25' },
  { id: 'm3', title: 'Gonjiam: Hospital Maldito', year: 2018, genre: 'Terror', director: 'Jung Bum-shik', duration: 95, rating: 4, review: 'El streaming de terror hecho película. Corea entiende el ritmo del miedo moderno: cámaras, likes y un psiquiátrico que no perdona.', poster_url: '/covers/gonjiam.jpg', trailer_url: 'https://www.youtube.com/watch?v=KKGJTgnkQA8', platform: 'Prime Video', instagram_url: 'https://www.instagram.com/fotogramas.malditos', featured: false, created_at: '2026-06-22' },
  { id: 'm2', title: 'REC', year: 2007, genre: 'Terror', director: 'Balagueró y Plaza', duration: 78, rating: 4, review: 'Found footage en estado puro: un edificio, una cámara y claustrofobia creciente. El último tramo sigue siendo de lo mejor del género.', poster_url: '/covers/rec.jpg', trailer_url: 'https://www.youtube.com/watch?v=KLizS5GFBQI', platform: 'Prime Video', instagram_url: 'https://www.instagram.com/fotogramas.malditos', featured: false, created_at: '2026-06-19' },
  { id: 'm1', title: 'Hereditary', year: 2018, genre: 'Terror', director: 'Ari Aster', duration: 127, rating: 4.5, review: 'El terror como herencia: una familia que se desmorona escena a escena hasta un final que no se olvida. Toni Collette está monumental.', poster_url: '/covers/hereditary.jpg', trailer_url: 'https://www.youtube.com/watch?v=V6wWKNij_1M', platform: 'Prime Video', instagram_url: 'https://www.instagram.com/fotogramas.malditos', featured: true, created_at: '2026-06-14' },
  { id: 'm4', title: 'Fenómeno Siniestro', year: 2011, genre: 'Terror', director: 'The Vicious Brothers', duration: 92, rating: 4, review: 'Un reality de fantasmas atrapado en su propio programa. Serie B con ideas brillantes y pasillos que cambian de lugar.', poster_url: '/covers/fenomeno-siniestro.jpg', trailer_url: 'https://www.youtube.com/watch?v=RAChPb4MvAU', platform: 'Netflix · Prime Video', instagram_url: 'https://www.instagram.com/fotogramas.malditos', featured: false, created_at: '2026-06-10' },
];

export const demoPortfolio: PortfolioItem[] = [
  {
    id: 'p4',
    slug: 'editor-pdf',
    title: 'Odiseo — Editor PDF',
    description: 'Herramienta web gratuita para trabajar con PDFs directamente en el navegador: unir, dividir, anotar y firmar documentos. Todo el procesamiento ocurre en el dispositivo del usuario — los archivos nunca se suben a un servidor. Desplegada en Netlify.',
    category: 'Aplicación Web',
    client: 'Proyecto propio',
    date: 'Julio 2026',
    technologies: ['HTML', 'CSS', 'JavaScript', 'Netlify'],
    cover_url: '/covers/work-pdf.svg',
    gallery: [],
    external_url: 'https://splendid-douhua-0ad145.netlify.app/',
    created_at: '2026-07-06',
  },
  {
    id: 'p1',
    slug: 'tarotec',
    title: 'TaroTec — landing de producto',
    description: 'Sitio de presentación para TaroTec, botana artesanal de malanga creada para InnovaTecNM 2026 (TecNM Orizaba): tres sabores, sección de beneficios, galería del producto y del stand, y canales de contacto. Desplegado en Netlify.',
    category: 'Desarrollo Web',
    client: 'TaroTec · InnovaTecNM 2026',
    date: '2026-07-01',
    technologies: ['HTML', 'CSS', 'JavaScript', 'Netlify'],
    cover_url: 'https://voluble-sunflower-7d8571.netlify.app/Sabores.jpeg',
    gallery: ['https://voluble-sunflower-7d8571.netlify.app/Natural.jpeg', 'https://voluble-sunflower-7d8571.netlify.app/Queso.jpeg', 'https://voluble-sunflower-7d8571.netlify.app/Habanero.jpeg', 'https://voluble-sunflower-7d8571.netlify.app/InnovaTec.jpg'],
    external_url: 'https://voluble-sunflower-7d8571.netlify.app/',
    created_at: '2026-07-01',
  },
  {
    id: 'p2',
    slug: 'fotogramas-malditos',
    title: 'Identidad — @fotogramas.malditos',
    description: 'Identidad visual completa para una cuenta de reseñas de cine de terror y sci-fi: estética oscura, estrellas doradas, plantillas de publicación y estructura editorial de sinopsis, reseña y calificación.',
    category: 'Branding',
    client: 'Proyecto propio',
    date: '2026-06-15',
    technologies: ['Dirección de arte', 'Instagram', 'Contenido'],
    cover_url: '/covers/work-brand.svg',
    gallery: [],
    external_url: 'https://www.instagram.com/fotogramas.malditos',
    created_at: '2026-06-15',
  },
  {
    id: 'p3',
    slug: 'archivo-clave-web',
    title: 'Archivo Clave — juego web multijugador',
    description: 'Juego de palabras clave por equipos con conexión P2P vía WebRTC, empaquetado en un solo archivo HTML y desplegado en hosting estático.',
    category: 'Videojuegos',
    client: 'Proyecto propio',
    date: '2026-06-25',
    technologies: ['JavaScript', 'PeerJS', 'WebRTC'],
    cover_url: '/covers/archivo.svg',
    gallery: [],
    external_url: null,
    created_at: '2026-06-25',
  },
];

export const demoSettings: SiteSettings = {
  tagline: 'Desarrollador de videojuegos, creador de contenido y apasionado por el cine.',
  hero_image: '/covers/hero-odiseo.jpg',
  theme_video: 'https://www.youtube.com/watch?v=_AAdae7diOU',
  now_banner: 'Esta semana: puliendo el sistema de baterías de la linterna en El Velador 🔦',
  footer_quote: 'Creating worlds, one game at a time.',
  socials: {
    instagram: 'https://www.instagram.com/fotogramas.malditos',
    github: 'https://github.com/',
    discord: 'https://discord.com/',
    email: 'hola@odiseo.dev',
  },
  about: {
    photo_url: '/covers/avatar.svg',
    bio:
      'Soy **Odiseo**, desarrollador independiente desde Orizaba, México.\n\nVengo de la gestión empresarial y estoy construyendo, en público, mi camino hacia la industria del videojuego: aprendiendo C# y Unity, escribiendo devlogs y diseñando **El Velador**, un horror atmosférico en primera persona.\n\nCuando no programo, analizo cine de terror, ciencia ficción y thriller en @fotogramas.malditos. Mi meta: desarrollar juegos en Vancouver.',
    skills: [
      { name: 'C# / Unity', level: 35 },
      { name: 'HTML / CSS / JavaScript', level: 60 },
      { name: 'Diseño de juego', level: 45 },
      { name: 'Análisis de cine', level: 90 },
      { name: 'Gestión de proyectos', level: 80 },
      { name: 'Inglés', level: 55 },
    ],
    experience: [
      { period: '2026 — hoy', role: 'Desarrollador indie', place: 'Odiseo Studio', description: 'Diseño y desarrollo de El Velador y proyectos web propios.' },
      { period: '2026 — hoy', role: 'Ingeniería de Software', place: 'Hybridge Education', description: 'Formación formal en desarrollo de software.' },
      { period: '2022 — 2026', role: 'Ingeniería en Gestión Empresarial', place: 'Instituto Tecnológico de Orizaba', description: 'Formación en gestión, análisis y estrategia.' },
    ],
  },
  seo: {
    title: 'Odiseo — Estudio independiente',
    description: 'Sitio oficial de Odiseo: desarrollo de videojuegos, devlogs, noticias, reseñas de cine y portafolio.',
  },
};
